#! This is a ytt template file for docker-compose.override.yaml
#! References:
#!   https://carvel.dev/ytt
#!   https://docs.docker.com/compose/extends/#adding-and-overriding-configuration
#!   https://github.com/enigmacurry/d.rymcg.tech#overriding-docker-composeyaml-per-instance

#! ### Standard project vars:
#@ load("@ytt:data", "data")
#@ project = data.values.project
#@ instance = data.values.instance
#@ context = data.values.context
#@ traefik_host = data.values.traefik_host
#@ ip_sourcerange = data.values.ip_sourcerange
#@ enable_mtls_auth = data.values.enable_mtls_auth == "true"
#@ mtls_authorized_certs = data.values.mtls_authorized_certs
#@ enabled_middlewares = []
#@ homepage_labels_enable = data.values.homepage_labels_enable == "true"
#@ homepage_group_soju = data.values.homepage_group_soju
#@ homepage_name_soju = data.values.homepage_name_soju
#@ homepage_icon_soju = data.values.homepage_icon_soju
#@ homepage_description_soju = data.values.homepage_description_soju
#@ homepage_show_stats_soju = data.values.homepage_show_stats_soju
#@ homepage_widget_enable = data.values.homepage_widget_enable == "true"
#@yaml/text-templated-strings
services:
  soju:
    #@ service = "soju"
    labels:
      - "backup-volume.stop-during-backup=true"
      #! Services must opt-in to be proxied by Traefik:
      - "traefik.enable=true"

      #! 'router' is the fully qualified key in traefik for this router/service: project + instance + service
      #@ router = "{}-{}-{}".format(project,instance,service)

      #! The host matching router rule:
      - "traefik.tcp.routers.(@= router @).rule=HostSNI(`(@= traefik_host @)`)"
      - "traefik.tcp.routers.(@= router @).tls=true"
      - "traefik.tcp.routers.(@= router @).tls.options=irc@file"
      - "traefik.tcp.routers.(@= router @).entrypoints=irc_bouncer"
      - "traefik.tcp.routers.(@= router @).service=(@= router @)"
      - "traefik.tcp.services.(@= router @).loadbalancer.server.port=6697"

      #@ enabled_middlewares.append("{}-ipallowlist".format(router))
      - "traefik.tcp.middlewares.(@= router @)-ipallowlist.ipallowlist.sourcerange=(@= ip_sourcerange @)"

      #@ if enable_mtls_auth:
      - "traefik.tcp.routers.(@= router @).tls.options=step_ca_mTLS@file"
       #@ if len(mtls_authorized_certs):
      - "traefik.tcp.middlewares.mtlsauth-(@= router @).plugin.certauthz.domains=(@= mtls_authorized_certs @)"
        #@ enabled_middlewares.append("mtlsauth-{}".format(router))
        #@ end
        #@ enabled_middlewares.append("mtls-header@file")
      #@ end
      
      #! Apply all middlewares (do this at the end!)
      - "traefik.tcp.routers.(@= router @).middlewares=(@= ','.join(enabled_middlewares) @)"

      #! Homepage (portal):
      #! See https://gethomepage.dev/configs/docker/#automatic-service-discovery
      #@ if homepage_labels_enable:
      - homepage.group=(@= homepage_group_soju @)
      - homepage.name=(@= homepage_name_soju @)
      - homepage.icon=(@= homepage_icon_soju @)
      - homepage.href=https://(@= traefik_host @)
      - homepage.description=(@= homepage_description_soju or traefik_host @)
      - homepage.showStats=(@= homepage_show_stats_soju @)
      #@ end
