services:
  uptime_kuma:
    image: ${UPTIME_KUMA_IMAGE}
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    volumes:
      - data:/app/data
    labels: []

volumes:
  data:
